In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("processed_clause_dataset.csv")

df.head()

,contract_title,clause_type,answer_text,question,context,has_clause,clause_length
0,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Document Name,DISTRIBUTOR AGREEMENT,Highlight the parts (if any) of this contract ...,EXHIBIT 10.6\n\n ...,True,21
1,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Agreement Date,"7th day of September, 1999.",Highlight the parts (if any) of this contract ...,EXHIBIT 10.6\n\n ...,True,27
2,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Effective Date,The term of this Agreement shall be ten (10)...,Highlight the parts (if any) of this contract ...,EXHIBIT 10.6\n\n ...,True,273
3,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Expiration Date,The term of this Agreement shall be ten (10)...,Highlight the parts (if any) of this contract ...,EXHIBIT 10.6\n\n ...,True,273
4,LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGRE...,Renewal Term,If Distributor comp...,Highlight the parts (if any) of this contract ...,EXHIBIT 10.6\n\n ...,True,338

In [4]:
import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r'\n+', ' ', text)

    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

df["clean_text"] = df["answer_text"].apply(clean_text)

In [5]:
df[["answer_text","clean_text"]].head()

,answer_text,clean_text
0,DISTRIBUTOR AGREEMENT,distributor agreement
1,"7th day of September, 1999.",7th day of september 1999
2,The term of this Agreement shall be ten (10)...,the term of this agreement shall be ten 10 yea...
3,The term of this Agreement shall be ten (10)...,the term of this agreement shall be ten 10 yea...
4,If Distributor comp...,if distributor complies with all of the terms ...

In [6]:
df["clean_text"].isnull().sum()

np.int64(0)

In [7]:
df["text_length"] = df["clean_text"].str.len()

df["text_length"].describe()

count    5694.000000
mean      275.654900
std       253.793159
min         0.000000
25%       114.000000
50%       216.500000
75%       361.000000
max      2730.000000
Name: text_length, dtype: float64

In [9]:
df.to_csv(
    "processed_clause_dataset_clean.csv",
    index=False
)